# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90b9f7d7992f3ff7ec4d0ef85601a096bf9339a4d2ff74f638ca9a79befa166ecdafdf91d2d68979b76c4311cea2a833e0fd101b3db96d87dffca2275eaddcf3

test:
  secret_key_base: d6b734a9f6e050f831494ef664f6072e8436f34ac24b844448c770f7d049f427fdccea8f88641ab39dbf71fdea76df818b872221a3aa4e83b9ea8c36c09a1eb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
